/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.BangLuongBUS;
import BUS.CTHDBUS;
import BUS.HoaDonBUS;
import BUS.MenuBUS;
import DAO.CTHDDAO;
import DAO.HoaDonDAO;
import DTO.BangLuongDTO;
import DTO.CTHDDTO;
import DTO.HoaDonDTO;
import DTO.MenuDTO;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class HoaDon_Form extends javax.swing.JFrame {
    private ArrayList<HoaDonDTO> list;
    DefaultTableModel model;
    private ArrayList<CTHDDTO> list1;
    DefaultTableModel model1;
    SimpleDateFormat ftNgay = new SimpleDateFormat("dd/MM/yyyy");
    public HoaDon_Form() {
        initComponents();
        this.setResizable(true); 
        ImageIcon img = new ImageIcon("src//Image//sanpham.png");
        this.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
        tbHoaDon.setShowGrid(true);
        tbCTHD.setShowGrid(true);
        list = new HoaDonBUS().getListHoaDon();
        list1= new CTHDBUS().getListCTHD();
        model = (DefaultTableModel) tbHoaDon.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "MaHoaDon", "MaNV", "SoLuong", "ThoiGian", "NgayLapHD"
        });
        model1 =(DefaultTableModel) tbCTHD.getModel();
        model1.setColumnIdentifiers(new Object[]{
            "STT", "MaHoaDon", "TenMon", "MaMon", "SoLuong", "Gia"
        });
        tbCTHD.getColumnModel().getColumn(0).setPreferredWidth(40);
        tbHoaDon.getColumnModel().getColumn(0).setPreferredWidth(40);
        clearTable();
        showTable();
        clearTableCTHD(); 
        showTableCTHD();   
    }
     
    public void showTable() {
        int i=1;
        for (HoaDonDTO s : list) {
            model.addRow(new Object[]{
                i++, s.getMaHoaDon(), s.getMaNV(), s.getSoLuong(), s.getThoiGian(),s.getNgayLapHD()
            });
        }
     }
    public void showTableCTHD() {
        int i=1;
        for (CTHDDTO s : list1) {
            model1.addRow(new Object[]{
                i++, s.getMaHoaDon(), s.getTenMon(), s.getMaMon(), s.getSoLuong(), s.getGia()
            });
        }
    }
    public void clearTable() {
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
    }
   public void clearTableCTHD() {
        for( int i = model1.getRowCount() - 1; i >= 0; i-- ) {
            model1.removeRow(i);
        }
    }
   /*public void showDB(){
        int selectrow=tblHoaDon_HoaDon.getSelectedRow();     
        txMaHoaDon.setText(tblHoaDon_HoaDon.getValueAt(selectrow,1).toString());
        boxMaNV.setSelectedItem(tblHoaDon_HoaDon.getValueAt(selectrow,2).toString());
        boxMaChuongTrinh.setSelectedItem(tblHoaDon_HoaDon.getValueAt(selectrow,3).toString());
        boxMaKhachHang.setSelectedItem(tblHoaDon_HoaDon.getValueAt(selectrow,4).toString());
        Date date;
        try {
            date = new  SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectrow,5));
            dateNgayLapHD.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDon_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        txGhiChu.setText(tblHoaDon_HoaDon.getValueAt(selectrow,6).toString());
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCTHD = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtThoiGian = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCTMaHoaDon = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        txtMaMon = new javax.swing.JTextField();
        txtCTSoLuong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSearchCTHD = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hóa Đơn");

        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDon);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sanpham.png"))); // NOI18N
        jLabel2.setText("Quản Lý Hóa Đơn");

        tbCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCTHD);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sanpham.png"))); // NOI18N
        jLabel3.setText("Chi Tiết Hóa Đơn");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key.png"))); // NOI18N
        jLabel1.setText("Mã Hóa Đơn");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key2.png"))); // NOI18N
        jLabel4.setText("Mã Nhân Viên");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/amount.png"))); // NOI18N
        jLabel5.setText("Số Lượng");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/time.png"))); // NOI18N
        jLabel6.setText("Thời Gian ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/date1.png"))); // NOI18N
        jLabel7.setText("Ngày Lập HĐ");

        txtDate.setDateFormatString("dd/MM/yyyy");
        txtDate.setMinimumSize(new java.awt.Dimension(139, 26));
        txtDate.setPreferredSize(new java.awt.Dimension(139, 26));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_more_48px.png"))); // NOI18N
        jLabel14.setText("  Tìm kiếm");
        jLabel14.setAlignmentX(0.5F);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thêm.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-bin-24.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_48px.png"))); // NOI18N
        jButton10.setText("Tìm kiếm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtThoiGian)
                            .addComponent(txtSoLuong)
                            .addComponent(txtMaNV)
                            .addComponent(txtMaHoaDon)
                            .addComponent(jTextFieldSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key.png"))); // NOI18N
        jLabel9.setText("Mã Hóa Đơn");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/name1.png"))); // NOI18N
        jLabel10.setText("Tên Món");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/key2.png"))); // NOI18N
        jLabel11.setText("Mã Món");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/amount.png"))); // NOI18N
        jLabel12.setText("Số Lượng");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gianhap.png"))); // NOI18N
        jLabel13.setText("Giá");

        txtCTMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTMaHoaDonActionPerformed(evt);
            }
        });

        txtTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMonActionPerformed(evt);
            }
        });

        txtMaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonActionPerformed(evt);
            }
        });

        txtCTSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTSoLuongActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Thêm.png"))); // NOI18N
        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        jButton6.setText("Sửa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-bin-24.png"))); // NOI18N
        jButton7.setText("Xóa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_more_48px.png"))); // NOI18N
        jLabel8.setText("  Tìm kiếm");
        jLabel8.setAlignmentX(0.5F);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_48px.png"))); // NOI18N
        jButton9.setText("Tìm kiếm");
        jButton9.setAlignmentX(0.5F);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCTSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCTMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldSearchCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(41, 41, 41)
                        .addComponent(jButton6)
                        .addGap(26, 26, 26)
                        .addComponent(jButton7)
                        .addGap(42, 42, 42)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCTMaHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCTSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//sửa hóa đơn
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HoaDonDTO s=new HoaDonDTO();
        s.setMaHoaDon(txtMaHoaDon.getText());
        s.setNgayLapHD(ftNgay.format(txtDate.getDate()));
        s.setThoiGian(txtThoiGian.getText());
        s.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        s.setMaNV(txtMaNV.getText());
        if (new HoaDonBUS().updateHoaDon(s)) {
            JOptionPane.showMessageDialog(null, "Sửa Thành Công.");
            } else {
                JOptionPane.showMessageDialog(null, "Sửa Thất Bại.");
            }
        clearTable();
        list = new HoaDonBUS().getListHoaDon();
        showTable();
    }//GEN-LAST:event_jButton2ActionPerformed
// thêm hóa đơn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HoaDonDTO s=new HoaDonDTO();
        s.setMaHoaDon(txtMaHoaDon.getText());
        s.setNgayLapHD(ftNgay.format(txtDate.getDate()));
        s.setThoiGian(txtThoiGian.getText());
        s.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        s.setMaNV(txtMaNV.getText());
        if (new HoaDonBUS().addHoaDon(s)) {
            JOptionPane.showMessageDialog(null, "Thêm Thành Công.");
            list.add(s);
        } else {
            JOptionPane.showMessageDialog(null, "Thêm Thất Bại.");
        }
        clearTable();
        showTable();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void showDB(){
        int selectrow=tbHoaDon.getSelectedRow();     
        txtMaHoaDon.setText(tbHoaDon.getValueAt(selectrow,1).toString());
        txtMaNV.setText(tbHoaDon.getValueAt(selectrow,2).toString());
        txtSoLuong.setText(tbHoaDon.getValueAt(selectrow,3).toString());
        txtThoiGian.setText(tbHoaDon.getValueAt(selectrow,4).toString());
        Date date;
        try {
            date = new  SimpleDateFormat("dd/MM/yyyy").parse((String)model.getValueAt(selectrow,5));
            txtDate.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDon_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void showDB1(){
        int selectrow=tbCTHD.getSelectedRow();
        txtCTMaHoaDon.setText(tbCTHD.getValueAt(selectrow,1).toString());
        txtTenMon.setText(tbCTHD.getValueAt(selectrow,2).toString());
        txtMaMon.setText(tbCTHD.getValueAt(selectrow,3).toString());
        txtCTSoLuong.setText(tbCTHD.getValueAt(selectrow,4).toString());
        txtGia.setText(tbCTHD.getValueAt(selectrow,5).toString());
    }
    public void showDBbb(){
       int selectrow=tbHoaDon.getSelectedRow();
       Object[] row= new Object[6];
       String ss=tbHoaDon.getValueAt(selectrow,1).toString();
       clearTableCTHD();
       int k=0;
        for (int i=0;i<list1.size();i++){
            if (list1.get(i).getMaHoaDon().toString().equals(ss)){
                
                k++;
                row[0]=k;
                row[1]=list1.get(i).getMaHoaDon();
                row[2]=list1.get(i).getTenMon();
                row[3]=list1.get(i).getMaMon();
                row[4]=list1.get(i).getSoLuong();
                row[5]=list1.get(i).getGia();
                model1.addRow(row);
            }
        }
    }
    private void tbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMouseClicked
        // TODO add your handling code here:
        showDB();
        showDBbb();
    }//GEN-LAST:event_tbHoaDonMouseClicked

    private void tbCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTHDMouseClicked
        // TODO add your handling code here:
         showDB1();
    }//GEN-LAST:event_tbCTHDMouseClicked
//refesh hóa đơn
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultTableModel=new DefaultTableModel();
        tbHoaDon.setModel(defaultTableModel);       
        HoaDonBUS hdBus=new HoaDonBUS();
        try {
                ArrayList<HoaDonDTO> hd=hdBus.getListHoaDon();
                defaultTableModel.addColumn("STT");
                defaultTableModel.addColumn("MaHoaDon");
                defaultTableModel.addColumn("MaNV");
                defaultTableModel.addColumn("SoLuong");
                defaultTableModel.addColumn("ThoiGian");
                defaultTableModel.addColumn("NgayNhap");
                int i=1;
                for (HoaDonDTO hd1: hd){
                    defaultTableModel.addRow(new Object[]{
                        i++, hd1.getMaHoaDon(), hd1.getMaNV(), hd1.getSoLuong(), hd1.getThoiGian(), hd1.getNgayLapHD()
                    });
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Không kết nối CSDL");
            }
    }//GEN-LAST:event_jButton4ActionPerformed
//xóa hóa đơn
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HoaDonDTO s= new HoaDonDTO();
        s.setMaHoaDon(txtMaHoaDon.getText());
         if (new HoaDonBUS().deleteHoaDon(s)) {
            JOptionPane.showMessageDialog(null, "Xóa Thành Công.");
        } else {
            JOptionPane.showMessageDialog(null, "Xóa Thất Bại.");
        }
        clearTable();
        list = new HoaDonBUS().getListHoaDon();
        showTable();
    }//GEN-LAST:event_jButton3ActionPerformed
//thêm chi tiết hd
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CTHDDTO ct= new CTHDDTO();
        ct.setMaHoaDon(txtCTMaHoaDon.getText());
        ct.setTenMon(txtTenMon.getText());
        ct.setMaMon(txtMaMon.getText());
        ct.setSoLuong(Integer.valueOf(txtCTSoLuong.getText()));
        ct.setGia(Integer.valueOf(txtGia.getText()));
        if (new CTHDBUS().addCTHD(ct)) {
            JOptionPane.showMessageDialog(null, "Thêm Thành Công.");
            list1.add(ct);
        } else {
            JOptionPane.showMessageDialog(null, "Thêm Thất Bại.");
        }
        clearTableCTHD();
        showTableCTHD();
    }//GEN-LAST:event_jButton5ActionPerformed
//sửa chi tiết hđ
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        CTHDDTO ct=new CTHDDTO();
        ct.setMaHoaDon(txtCTMaHoaDon.getText());
        ct.setTenMon(txtTenMon.getText());
        ct.setMaMon(txtMaMon.getText());
        ct.setSoLuong(Integer.valueOf(txtCTSoLuong.getText()));
        ct.setGia(Integer.parseInt(txtGia.getText()));
        if (new CTHDBUS().updateCTHD(ct)) {
            JOptionPane.showMessageDialog(null, "Sửa Thành Công.");
        } else {
            JOptionPane.showMessageDialog(null, "Sửa Thất Bại.");
        }
        clearTableCTHD();
        list1 = new CTHDBUS().getListCTHD();
        showTableCTHD();
    }//GEN-LAST:event_jButton6ActionPerformed
//xóa chi tiết hđ
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CTHDDTO ct= new CTHDDTO();
        ct.setMaHoaDon(txtCTMaHoaDon.getText());
         if (new CTHDBUS().deleteCTHD(ct)) {
            JOptionPane.showMessageDialog(null, "Xóa Thành Công.");
        } else {
            JOptionPane.showMessageDialog(null, "Xóa Thất Bại.");
        }
        clearTableCTHD();
        list1 = new CTHDBUS().getListCTHD();
        showTableCTHD();
    }//GEN-LAST:event_jButton7ActionPerformed
//refesh chi tiết hđ
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultTableModel=new DefaultTableModel();
        tbCTHD.setModel(defaultTableModel);       
        CTHDBUS cthdBus=new CTHDBUS();
        try {
                ArrayList<CTHDDTO> chitiethd=cthdBus.getListCTHD();
                defaultTableModel.addColumn("STT");
                defaultTableModel.addColumn("MaHoaDon");
                defaultTableModel.addColumn("TenMon");
                defaultTableModel.addColumn("MaMon");
                defaultTableModel.addColumn("SoLuong");
                defaultTableModel.addColumn("Gia");
                int i=1;
                for (CTHDDTO cthd1: chitiethd){
                    defaultTableModel.addRow(new Object[]{
                        i++, cthd1.getMaHoaDon(), cthd1.getTenMon(), cthd1.getMaMon(), cthd1.getSoLuong(), cthd1.getGia()
                    });
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Không kết nối CSDL");
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtCTMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTMaHoaDonActionPerformed

    private void txtTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMonActionPerformed

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed

    private void txtCTSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTSoLuongActionPerformed
//tìm kiếm hóa đơn
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String keyString=jTextFieldSearch.getText();
        if(keyString.equals("")){
            JOptionPane.showMessageDialog(null, "Hãy nhập mã hóa đơn cần tìm");
            jTextFieldSearch.requestFocus(true);
        }else {
            tbHoaDon.removeAll();
            tbHoaDon.revalidate();
            tbHoaDon.repaint();
            DefaultTableModel defaultTableModel=new DefaultTableModel();
            tbHoaDon.setModel(defaultTableModel);           
//setting lại table hóa đơn
            HoaDonBUS hdBus=new HoaDonBUS();
            try {
                ArrayList<HoaDonDTO> hoadon=hdBus.searchHoaDon(keyString);
                defaultTableModel.addColumn("STT");
                defaultTableModel.addColumn("MaHoaDon");
                defaultTableModel.addColumn("MaNhanVien");
                defaultTableModel.addColumn("SoLuong");
                defaultTableModel.addColumn("ThoiGian");
                defaultTableModel.addColumn("NgayNhap");
                int i=1;
                for (HoaDonDTO hd1: hoadon){
                    defaultTableModel.addRow(new Object[]{
                        i++, hd1.getMaHoaDon(), hd1.getMaNV(), hd1.getSoLuong(), hd1.getThoiGian(),hd1.getNgayLapHD()
                    });
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy");
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed
//tìm kiếm chi tiết hóa đơn
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String keyString=jTextFieldSearchCTHD.getText();
        if(keyString.equals("")){
            JOptionPane.showMessageDialog(null, "Hãy nhập mã hóa đơn cần tìm");
            jTextFieldSearchCTHD.requestFocus(true);
        }else {
            tbCTHD.removeAll();
            tbCTHD.revalidate();
            tbCTHD.repaint();
            DefaultTableModel defaultTableModel=new DefaultTableModel();
            tbCTHD.setModel(defaultTableModel);           
//setting lại table  CTHD
           CTHDBUS CTHDBus=new CTHDBUS();
            try {
                ArrayList<CTHDDTO> cthd=CTHDBus.searchCTHD(keyString);
                defaultTableModel.addColumn("STT");
                defaultTableModel.addColumn("MaHoaDon");
                defaultTableModel.addColumn("TenMon");
                defaultTableModel.addColumn("MaMon");
                defaultTableModel.addColumn("SoLuong");
                defaultTableModel.addColumn("Gia");
                int i=1;
                for (CTHDDTO cthd1: cthd){
                    defaultTableModel.addRow(new Object[]{
                        i++, cthd1.getMaMon(), cthd1.getTenMon(), cthd1.getMaMon(), cthd1.getSoLuong(), cthd1.getGia()
                    });
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDon_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSearchCTHD;
    private javax.swing.JTable tbCTHD;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JTextField txtCTMaHoaDon;
    private javax.swing.JTextField txtCTSoLuong;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
